theme: jekyll-theme-cayman
title: Aman Jindal's Blog
tagline: Easy websites with GitHub Pages
description: A collection of my ramblings

# Build settings
markdown: kramdown
kramdown:
   math_engine: mathjax
   
