theme: jekyll-theme-architect
title: Aman Jindal's Blog
tagline: Easy websites with GitHub Pages
description: A collection of my ramblings

# Build settings
markdown: kramdown
kramdown:
   math_engine: mathjax

# Includes an icon in the footer for each username you enter
footer-links:
  dribbble:
  email:
  facebook:
  flickr:
  github: hbk91
  instagram:
  linkedin: amanjindal1
  pinterest:
  rss: # just type anything here for a working RSS icon
  twitter:
  stackoverflow: # your stackoverflow profile, e.g. "users/50476/bart-kiers"
  youtube: # channel/<your_long_string> or user/<user-name>
  googleplus: # anything in your profile username that comes after plus.google.com/
   
